parser: babel-eslint

# So that parent files don't get applied
root: true

env:
  es6: true
  node: true

parserOptions:
  sourceType: module

rules:
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: false
  comma-spacing:
    - error
    -
      before: false
      after: true
  comma-style:
    - error
    - last
  computed-property-spacing:
    - error
    - never
  eqeqeq:
    - error
    - smart
  eol-last:
    - error
  indent:
    - error
    - 2
  key-spacing:
    - error
  keyword-spacing:
    - error
  linebreak-style:
    - error
    - unix
  no-unused-expressions:
    - error
  no-unused-vars:
    - error
  no-shadow:
    - error
  no-spaced-func:
    - error
  no-multi-spaces:
    - error
  no-undef:
    - error
  no-dupe-keys:
    - error
  no-dupe-args:
    - error
  no-duplicate-case:
    - error
  no-cond-assign:
    - error
  no-extra-semi:
    - error
  no-extra-boolean-cast:
    - error
  no-trailing-spaces:
    - error
  no-unreachable:
    - error
  no-var:
    - error
  object-curly-spacing:
    - error
    - never
  prefer-arrow-callback:
    - error
  prefer-const:
    - error
  quotes:
    - error
    - single
    - avoid-escape
  semi-spacing:
    - error
  semi:
    - error
    - always
  space-infix-ops:
    - error
  space-unary-ops:
    - error
    -
      words: true
      nonwords: false
